apiVersion: v1
items:
- apiVersion: v1
  data:
    apikey: NUdBZDNFbVJFLTY4OS1pUmVtNQ==
    password: UGFzc3cwcmQ=
    username: YWJiYWJl
  kind: Secret
  metadata:
    annotations:
      avp.kubernetes.io/path: credentials/data/app
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"avp.kubernetes.io/path":"credentials/data/app"},"labels":{"argocd.argoproj.io/instance":"vault-secret-app-demo"},"name":"app-crds","namespace":"vault-secret"},"stringData":{"apikey":"5GAd3EmRE-689-iRem5","password":"Passw0rd","username":"abbabe"},"type":"Opaque"}
    creationTimestamp: "2023-04-25T16:34:03Z"
    labels:
      argocd.argoproj.io/instance: vault-secret-app-demo
    name: app-crds
    namespace: vault-secret
    resourceVersion: "365868"
    uid: 7a9f0cec-70a7-4c8b-b9eb-2067a45e82ed
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
